apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: nginx-examples
deploy:
  kubectl:
    manifests:
    - k8s/*.yml
portForward:
- resourceType: service
  resourceName: nginx-service
  port: 8080
  localPort: 8080
