---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
    volumeMounts:
    - name: nginx-configuration-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  volumes:
  - name: nginx-configuration-volume
    configMap:
      name: nginx-configuration-configmap
      items:
      - key: nginx.conf
        path: nginx.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration-configmap
data:
  nginx.conf: |
    events {}

    http {
      upstream backends {
        server backend1-service:18443;
        server backend1-service:28443;
      }

      server {
        listen       8080;
        server_name  localhost;

        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }

        location /backends {
          proxy_set_header  test "nginx";
          proxy_pass        https://backends/headers.json;
        }
      }
    }
